### ISSUE TITLE
Rename to more specific repo?

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/sdr-metrics-api#14]
'Metrics' is a very broad term, in use across DLSS, Stanford and the world. As a globally-visible project, could this repo  be renamed to something with a tighter scope, e.g. 'sdr metrics' to avoid confusion and disambiguation issues?

**Comment by thatbudakguy** [comment]
the name of the repo is `sul-dlss/metrics`, so I'm not sure I understand the beyond-stanford concerns (although i suppose it doesn't _need_ to be public). i think the name accurately reflects the uncertainty about scope: right now it's confined to a few statistics about usage of sdr objects, but it's very possible it could expand to cover non-sdr objects.

is this related to https://github.com/sul-dlss/operations-tasks/issues/3511 at all? if the name is likely to cause problems on the systems side because of vm naming or what have you, i think it's totally fine for things to be called `sul-metrics-abc`, etc. we already follow that pattern with e.g. purl.
